// ============================================================
//  PRODUCT CATALOG — VeronikaK
//  AUTO-GENERATED by sync-products.js on 24/02/2026
//  25 products synced from https://sinuguru.square.site
//  Re-run: node sync-products.js --key=YOUR_OPENAI_KEY
// ============================================================

const SQUARE_SHOP = "https://sinuguru.square.site";

const products = [
  {
    id: 1,
    name: "12mm Round Beaded With Golden Coloured Stars Bracelet",
    tag: "Best Seller ⭐",
    category: "Bracelets",
    description: "Handmade with 12mm round pink and blue beads, this bracelet dazzles with golden star accents. Elevate your style with this whimsical piece.",
    price: "£6.00",
    emoji: "⭐",
    bg: "#fff0f9",
    url: "https://sinuguru.square.site/product/12mm-round-beaded-with-golden-coloured-stars-bracelet/1",
    imageUrl: "images/product-01.jpeg"
  },
  {
    id: 2,
    name: "10mm Brown, Yellow Round Beaded With Golden Coloured Stars Bracelet",
    tag: "Popular 💕",
    category: "Bracelets",
    description: "Handcrafted with vibrant yellow and rich brown beads, this bracelet is adorned with golden star accents. Perfect for adding a touch of elegance to any outfit.",
    price: "£6.00",
    emoji: "🤎",
    bg: "#efebe9",
    url: "https://sinuguru.square.site/product/10mm-brown-yellow-round-beaded-with-golden-coloured-stars-bracelet/5",
    imageUrl: "images/product-02.jpeg"
  },
  {
    id: 3,
    name: "10mm Brown, Yellow Round Beaded With Golden Coloured Octahedron  Bracelet",
    tag: "Trending 🔥",
    category: "Bracelets",
    description: "This handmade bracelet features striking 10mm brown and yellow crackle beads, elegantly paired with golden octahedron accents, perfect for adding a touch of sophistication.",
    price: "£6.00",
    emoji: "🤎",
    bg: "#efebe9",
    url: "https://sinuguru.square.site/product/10mm-brown-yellow-round-beaded-with-golden-coloured-octahedron-bracelet/6",
    imageUrl: "images/product-03.jpeg"
  },
  {
    id: 4,
    name: "8mm Blue and Yellow Round Beaded With Golden Coloured Cube and Barrell Bracelet",
    tag: "New 🌸",
    category: "Bracelets",
    description: "Handmade with vibrant 8mm blue and yellow round beads, accented by golden cube and barrel details, this bracelet adds a pop of color and elegance.",
    price: "£6.00",
    emoji: "💙",
    bg: "#e3f2fd",
    url: "https://sinuguru.square.site/product/8mm-blue-and-yellow-round-beaded-with-golden-coloured-cube-and-barrell-bracelet/7",
    imageUrl: "images/product-04.jpeg"
  },
  {
    id: 5,
    name: "clear 1",
    tag: "Sale 🏷️",
    category: "Bracelets",
    description: "Handmade with iridescent clear beads, this elegant bracelet captures the light beautifully, adding a touch of sophistication to any outfit. Elevate your style instantly.",
    price: "£6.00",
    emoji: "🔮",
    bg: "#e8eaf6",
    url: "https://sinuguru.square.site/product/clear-1/10",
    imageUrl: "images/product-05.jpeg"
  },
  {
    id: 6,
    name: "clear 2",
    tag: "Handmade 💛",
    category: "Bracelets",
    description: "Handmade with delicate crystal-clear beads accented by soft pink threads, this bracelet adds a touch of elegance to any ensemble. Perfect for a charming style boost.",
    price: "£6.00",
    emoji: "🔮",
    bg: "#e8eaf6",
    url: "https://sinuguru.square.site/product/clear-2/11",
    imageUrl: "images/product-06.jpeg"
  },
  {
    id: 7,
    name: "Type 5",
    tag: "Gift Idea 🎁",
    category: "Bracelets",
    description: "Embrace timeless elegance with this handmade bracelet, featuring intricately detailed silver-toned floral beads. Perfect for adding a touch of sophistication to any ensemble.",
    price: "£6.00",
    emoji: "🪩",
    bg: "#fff0f9",
    url: "https://sinuguru.square.site/product/type-5/18",
    imageUrl: "images/product-07.jpeg"
  },
  {
    id: 8,
    name: "Type 6",
    tag: "Unique 💎",
    category: "Bracelets",
    description: "Handmade with elegant crystal-clear beads and intricate silver accents, this bracelet adds a touch of sophistication to any ensemble. Elevate your style today!",
    price: "£6.00",
    emoji: "🔮",
    bg: "#fff0f9",
    url: "https://sinuguru.square.site/product/type-6/19",
    imageUrl: "images/product-08.jpeg"
  },
  {
    id: 9,
    name: "Type 8",
    tag: "Best Seller ⭐",
    category: "Bracelets",
    description: "Handmade with intricate silver floral and faceted beads, this bracelet exudes elegance and charm. Perfect for adding a touch of sophistication to any outfit.",
    price: "£6.00",
    emoji: "🌟",
    bg: "#fff0f9",
    url: "https://sinuguru.square.site/product/type-8/21",
    imageUrl: "images/product-09.jpeg"
  },
  {
    id: 10,
    name: "Braided 3",
    tag: "Popular 💕",
    category: "Braided",
    description: "Handmade with vibrant fruit charms and intricate black braiding, this playful bracelet adds a splash of whimsy to any outfit. Perfect for uplifted spirits!",
    price: "£6.00",
    emoji: "🎋",
    bg: "#f1f8e9",
    url: "https://sinuguru.square.site/product/braided-3/25",
    imageUrl: "images/product-10.jpeg"
  },
  {
    id: 11,
    name: "Braided 6",
    tag: "Trending 🔥",
    category: "Braided",
    description: "Handmade with a vibrant array of pastel cube beads, this braided bracelet adds a playful touch to any outfit. Perfect for brightening your day!",
    price: "£6.00",
    emoji: "🪢",
    bg: "#f1f8e9",
    url: "https://sinuguru.square.site/product/braided-6/28",
    imageUrl: "images/product-11.jpeg"
  },
  {
    id: 12,
    name: "Braided 9",
    tag: "New 🌸",
    category: "Braided",
    description: "Handmade with meticulous care, this black braided bracelet features distinctive square beads for a sleek, modern touch. Elevate your style effortlessly today.",
    price: "£6.00",
    emoji: "🌻",
    bg: "#f1f8e9",
    url: "https://sinuguru.square.site/product/braided-9/31",
    imageUrl: "images/product-12.jpeg"
  },
  {
    id: 13,
    name: "Braided 10",
    tag: "Sale 🏷️",
    category: "Braided",
    description: "Handmade with intricate braiding and sleek black beads, this chic bracelet features eye-catching silver accents—perfect for adding a modern edge to any outfit.",
    price: "£6.00",
    emoji: "🍃",
    bg: "#f1f8e9",
    url: "https://sinuguru.square.site/product/braided-10/32",
    imageUrl: "images/product-13.jpeg"
  },
  {
    id: 14,
    name: "Braided 12",
    tag: "Handmade 💛",
    category: "Braided",
    description: "Handmade with care, this elegant bracelet features metallic letter beads spelling \"SMILE\" on a chic braided cord. Wear it daily for a touch of positivity.",
    price: "£6.00",
    emoji: "🌻",
    bg: "#f1f8e9",
    url: "https://sinuguru.square.site/product/braided-12/34",
    imageUrl: "images/product-14.jpeg"
  },
  {
    id: 15,
    name: "Kids 1",
    tag: "Gift Idea 🎁",
    category: "Kids",
    description: "Brighten up playtime with this handmade bracelet featuring colorful cube beads and transparent accents. Perfect for little fashionistas who love vibrant, playful accessories!",
    price: "£6.00",
    emoji: "🎀",
    bg: "#e8f5e9",
    url: "https://sinuguru.square.site/product/kids-1/36",
    imageUrl: "images/product-15.jpeg"
  },
  {
    id: 16,
    name: "Kid 2",
    tag: "Unique 💎",
    category: "Kids",
    description: "Handmade with vibrant, fruity beads, this playful bracelet adds a splash of color and whimsy to any outfit. Perfect for little trendsetters!",
    price: "£6.00",
    emoji: "🎀",
    bg: "#e8f5e9",
    url: "https://sinuguru.square.site/product/kid-2/37",
    imageUrl: "images/product-16.jpeg"
  },
  {
    id: 17,
    name: "Kids 3",
    tag: "Best Seller ⭐",
    category: "Kids",
    description: "Bright and playful, this handmade bracelet features vibrant flower beads paired with sparkling crystals. A joyful accessory for any little fashionista!",
    price: "£6.00",
    emoji: "🎡",
    bg: "#e8f5e9",
    url: "https://sinuguru.square.site/product/kids-3/38",
    imageUrl: "images/product-17.jpeg"
  },
  {
    id: 18,
    name: "Earrings 2",
    tag: "Popular 💕",
    category: "Earrings",
    description: "Handmade with rich wooden cross pendants, these earrings feature elegant silver hooks, offering a touch of rustic charm to any ensemble. Elevate your style effortlessly.",
    price: "£6.00",
    emoji: "🌺",
    bg: "#fce4f3",
    url: "https://sinuguru.square.site/product/earrings-2/40",
    imageUrl: "images/product-18.jpeg"
  },
  {
    id: 19,
    name: "Earrings 3",
    tag: "Trending 🔥",
    category: "Earrings",
    description: "Handmade with delicate silver hearts and elegant pearl beads, these enchanting earrings add a touch of romance to any outfit. Perfect for a timeless elegance.",
    price: "£6.00",
    emoji: "✨",
    bg: "#fce4f3",
    url: "https://sinuguru.square.site/product/earrings-3/41",
    imageUrl: "images/product-19.jpeg"
  },
  {
    id: 20,
    name: "Earrings 5",
    tag: "New 🌸",
    category: "Earrings",
    description: "Handmade with elegant silver-tone hearts and lustrous pearls, these earrings add charm and sophistication to any outfit. Perfect for capturing timeless elegance.",
    price: "£6.00",
    emoji: "🪩",
    bg: "#fce4f3",
    url: "https://sinuguru.square.site/product/earrings-5/43",
    imageUrl: "images/product-20.jpeg"
  },
  {
    id: 21,
    name: "Earrings 6",
    tag: "Sale 🏷️",
    category: "Earrings",
    description: "Handmade with silver bow charms and elegant pearl beads, these earrings add a touch of whimsy and grace to any outfit. Make them yours today!",
    price: "£6.00",
    emoji: "🪩",
    bg: "#fce4f3",
    url: "https://sinuguru.square.site/product/earrings-6/44",
    imageUrl: "images/product-21.jpeg"
  },
  {
    id: 22,
    name: "Earrings 7",
    tag: "Handmade 💛",
    category: "Earrings",
    description: "Delicate handmade earrings featuring intricate silver-tone butterflies with elegant pearl accents. Perfect for adding a whimsical touch to any outfit.",
    price: "£6.00",
    emoji: "🌺",
    bg: "#fce4f3",
    url: "https://sinuguru.square.site/product/earrings-7/45",
    imageUrl: "images/product-22.jpeg"
  },
  {
    id: 23,
    name: "Earrings 8",
    tag: "Gift Idea 🎁",
    category: "Earrings",
    description: "Handmade butterfly earrings featuring intricate gold detailing and sparkling crystal centers, perfect for adding a touch of whimsy and elegance to any outfit.",
    price: "£6.00",
    emoji: "💜",
    bg: "#fce4f3",
    url: "https://sinuguru.square.site/product/earrings-8/46",
    imageUrl: "images/product-23.jpeg"
  },
  {
    id: 24,
    name: "Earrings 9",
    tag: "Unique 💎",
    category: "Earrings",
    description: "Handmade and vibrant, these earrings showcase cheerful citrus and berry charms with delicate pearls. Add a playful pop to any outfit!",
    price: "£6.00",
    emoji: "💜",
    bg: "#fce4f3",
    url: "https://sinuguru.square.site/product/earrings-9/47",
    imageUrl: "images/product-24.jpeg"
  },
  {
    id: 25,
    name: "Earrings 10",
    tag: "Best Seller ⭐",
    category: "Earrings",
    description: "Brighten your day with these handmade earrings featuring vibrant citrus-inspired beads in orange, pink, and green, perfect for adding a zingy touch to any outfit!",
    price: "£6.00",
    emoji: "🪩",
    bg: "#fce4f3",
    url: "https://sinuguru.square.site/product/earrings-10/48",
    imageUrl: "images/product-25.jpeg"
  }
];
